// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnVMydALzqkGj75Z67VeWw2iTISuCe08Y',
    appId: '1:815524268500:web:5a7a45ddd41d125969ee41',
    messagingSenderId: '815524268500',
    projectId: 'reservas-1132b',
    authDomain: 'reservas-1132b.firebaseapp.com',
    storageBucket: 'reservas-1132b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1tyBCgC4ojnYIFif6fvmZOPnzdR60Bw',
    appId: '1:815524268500:android:d883ea5f0eb7aa3c69ee41',
    messagingSenderId: '815524268500',
    projectId: 'reservas-1132b',
    storageBucket: 'reservas-1132b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfxoYM4lNVKbB6oRT_NoWl2t_5OgVtj5g',
    appId: '1:815524268500:ios:e9ce6577d123b30f69ee41',
    messagingSenderId: '815524268500',
    projectId: 'reservas-1132b',
    storageBucket: 'reservas-1132b.firebasestorage.app',
    iosBundleId: 'com.example.proyectoreservasihc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfxoYM4lNVKbB6oRT_NoWl2t_5OgVtj5g',
    appId: '1:815524268500:ios:e9ce6577d123b30f69ee41',
    messagingSenderId: '815524268500',
    projectId: 'reservas-1132b',
    storageBucket: 'reservas-1132b.firebasestorage.app',
    iosBundleId: 'com.example.proyectoreservasihc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnVMydALzqkGj75Z67VeWw2iTISuCe08Y',
    appId: '1:815524268500:web:52b13235a39862f869ee41',
    messagingSenderId: '815524268500',
    projectId: 'reservas-1132b',
    authDomain: 'reservas-1132b.firebaseapp.com',
    storageBucket: 'reservas-1132b.firebasestorage.app',
  );
}
